name: "release-auto-blogger"
description: "A github action to deploy blogs automatically to hashnode"

inputs:
  project-name:
    description: "The name of the project for the blog"
    required: true

  hashnode-host:
    description: "The hashnode host e.g amosmachora.hashnode.dev"
    required: true

  subtitle:
    description: "Subtitle for your blogs"

  cover-image:
    description: "A cover image url for the blog"

runs:
  using: "node20"
  pre: "npm install"
  main: "dist/index.js"

branding:
  icon: "book"
  color: "yellow"
