name: "release-auto-blogger"
description: "A github action to deploy blogs automatically to hashnode"

inputs:
  project-name:
    description: "The name of the project for the blog"
    required: true

  hashnode-host:
    description: "The hashnode host e.g amosmachora.hashnode.dev"
    required: true

  subtitle:
    description: "Subtitle for your blogs"

  cover-image:
    description: "A cover image url for the blog"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm action 8
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Set up Node 20
      uses: actions/setup-node@v3
      with:
        cache: "pnpm"
        node-version: 20

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: build
      run: pnpm run build
      shell: bash
      working-directory: ${{ github.action_path }}

    - run: node dist/index.js
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        PROJECT_NAME: ${{ inputs.project-name }}
        HASHNODE_HOST: ${{ inputs.hashnode-host }}
        SUBTITLE: ${{ inputs.subtitle }}
        COVER_IMAGE: ${{ inputs.cover-image }}
        BLOG_ONLY: ${{ inputs.blog-only }}
        FILES: ${{ inputs.files }}
        GITHUB_WORKSPACE: ${{ github.workspace }}

branding:
  icon: "book"
  color: "yellow"
