name: "release-auto-blogger"
description: "A github action to deploy blogs automatically to hashnode"
# inputs:
#   who-to-greet: # id of input
#     description: "Who to greet"
#     required: true
#     default: "World"
runs:
  using: "node20"
  main: "dist/index.js"
