name: "release-auto-blogger"
description: "A github action to deploy blogs automatically to hashnode"

inputs:
  project-name:
    description: "The name of the project for the blog"
    required: true

  hashnode-host:
    description: "The hashnode host e.g amosmachora.hashnode.dev"
    required: true

  subtitle:
    description: "Subtitle for your blogs"

  cover-image:
    description: "A cover image url for the blog"

runs:
  using: "composite"
  main: "dist/index.js"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Run main script
      run: node dist/index.js
      shell: bash
